site:
  title: "Sfruttare al massimo l'Event Bus di Quarkus"
  url: https://amusarra.github.io/eventbus-logging-filter-jaxrs-docs
  start_page: eventbus-logging-filter-jaxrs::index.adoc
  robots: allow

content:
  sources:
    - url: .
      start_path: docs
      branches:
        - HEAD

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    page-pagination: ''
    source-highlighter: highlight.js
    idprefix: ''
    idseparator: '-'
    sectnums: ''
    sectnumlevels: 3
    experimental: ''
    allow-uri-read: ''
    project-name: eventbus-logging-filter-jaxrs
    project-version: '1.3.0'
    github-url: 'https://github.com/amusarra/eventbus-logging-filter-jaxrs'
    github-docs-url: 'https://github.com/amusarra/eventbus-logging-filter-jaxrs-docs'
    quarkus-version: '3.9.2'
  extensions:
    - asciidoctor-kroki

antora:
  extensions:
    - require: '@antora/lunr-extension'

output:
  dir: ./target/antora-site
  clean: true



