=== Realizzazione del Dispatcher e Event Handler

Siamo quasi al termine! Non rimane altro che implementare gli ultimi componenti, ovvero, il Dispatcher e gli Event Handler. In questo settimo step, il tag finale di riferimento è https://github.com/amusarra/eventbus-logging-filter-jaxrs/tree/step-7.1.3[step-7.1.3].

Iniziamo con il Dispatcher. Questo componente è sempre un consumer registrato sull'Event Bus sull'indirizzo virtuale definito in `app.eventbus.consumer.dispatcher.address` sul file di configurazione  `application.properties` dell'applicazione Quarkus.

Il Dispatcher conosce gli indirizzi virtuali degli Event Handler a cui inoltrare i messaggi ricevuti leggendo gli *header* dal messaggio che ha ricevuto. A seguire l'estratto di codice del consumer `HttpRequestConsumer` revisionato per includere le informazioni per il Dispatcher. La stessa revisione è stata fatta per il consumer `HttpResponseConsumer`.

Rispetto alla precedente versione del consumer, è stata aggiunta la lettura dell'indirizzo virtuale del Dispatcher dalla configurazione `app.eventbus.consumer.dispatcher.address` e la lista degli Event Handler dalla configurazione `app.eventbus.consumer.event.handler.addresses` .

È stato creato inoltre l'oggetto `DeliveryOptions` per specificare le opzioni di consegna del messaggio e in particolare gli header `SOURCE_VIRTUAL_ADDRESS`, `SOURCE_COMPONENT` e `TARGET_VIRTUAL_ADDRESSES`.

L'header d'interesse per il Dispatcher è `TARGET_VIRTUAL_ADDRESSES` che contiene l'elenco degli indirizzi virtuali degli Event Handler a cui inoltrare il messaggio. Il Dispatcher legge questo header e inoltra il messaggio a tutti gli Event Handler specificati; le informazioni presenti sull'header del messaggio sono quindi necessarie per applicare "regole di routing" ai messaggi da inoltrare.

<<<

[source,java,title="*Code 6* - Revisione del consumer `HttpRequestConsumer` per includere le informazioni per il Dispatcher"]
....
...
@ApplicationScoped
public class HttpRequestConsumer {

  @ConfigProperty(name = "app.eventbus.consumer.dispatcher.address")
  String dispatcherVirtualAddress;

  @ConfigProperty(name = "app.eventbus.consumer.event.handler.addresses")
  List<String> eventHandlerVirtualAddresses;

  public static final String SOURCE_VIRTUAL_ADDRESS = "source-virtual-address";

  public static final String SOURCE_COMPONENT = "source-component";

  public static final String TARGET_VIRTUAL_ADDRESSES = "target-virtual-addresses";

  void onStart(@Observes StartupEvent ev) {
  	...
  }

  // Method to handle the event
  public void handleEvent(Message<JsonObject> message) {
    // Creare le opzioni di consegna desiderate
    DeliveryOptions options = new DeliveryOptions()
        .addHeader(TARGET_VIRTUAL_ADDRESSES, String.join(",", eventHandlerVirtualAddresses))
        .addHeader(SOURCE_VIRTUAL_ADDRESS, httpRequestVirtualAddress)
        .addHeader(SOURCE_COMPONENT, HttpRequestConsumer.class.getName());

        eventBus.publish(dispatcherVirtualAddress, message.body(), options);
  }
}
....

Dobbiamo quindi implementare il Dispatcher tenendo conto delle informazioni presenti sull'header `TARGET_VIRTUAL_ADDRESSES`  e che dobbiamo ricevere l'esito dell'elaborazione del messaggio da parte degli Event Handler. A seguire il codice completo del Dispatcher.

Il metodo `void handleEvent(Message<JsonObject> message)` è responsabile di:

. leggere gli header dal messaggio ricevuto e in particolare l'header `TARGET_VIRTUAL_ADDRESSES` che contiene gli indirizzi virtuali degli Event Handler;
. inviare il messaggio a tutti gli Event Handler specificati nell'header `TARGET_VIRTUAL_ADDRESSES` (tramite il metodo `eventBus.<String>request()`) e attende (in async mode) l'esito dell'elaborazione del messaggio da parte degli Event Handler. L'esito dell'elaborazione è loggato in console.

[source,java,title="*Code 7* - Implementazione del Dispatcher"]
....
package it.dontesta.eventbus.consumers.events.handlers;

import io.quarkus.runtime.StartupEvent;
import io.smallrye.mutiny.Uni;
import io.vertx.core.json.JsonObject;
import io.vertx.mutiny.core.eventbus.EventBus;
import io.vertx.mutiny.core.eventbus.Message;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;
import java.util.List;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

@ApplicationScoped
public class Dispatcher {
  @Inject
  EventBus eventBus;

  @Inject
  Logger log;

  @ConfigProperty(name = "app.eventbus.consumer.dispatcher.address")
  String dispatcherVirtualAddress;

  public static final String SOURCE_VIRTUAL_ADDRESS = "source-virtual-address";

  public static final String SOURCE_COMPONENT = "source-component";

  public static final String TARGET_VIRTUAL_ADDRESSES = "target-virtual-addresses";

  void onStart(@Observes StartupEvent ev) {
    log.debugf(
        "Registering the dispatcher to the event bus for the event handler at addresses: {%s}",
        dispatcherVirtualAddress);

    eventBus.consumer(dispatcherVirtualAddress, this::handleEvent);
  }

  // Method to handle the event
  public void handleEvent(Message<JsonObject> message) {
    // Leggere gli header dalle DeliveryOptions
    String sourceVirtualAddress = message.headers().get(SOURCE_VIRTUAL_ADDRESS);
    String sourceComponent = message.headers().get(SOURCE_COMPONENT);
    List<String> targetVirtualAddressesList =
        List.of(message.headers().get(TARGET_VIRTUAL_ADDRESSES).split(","));

    log.debugf(
        new StringBuilder().append(
                "Received event message from source virtual address: %s and source component: %s ")
            .append("for the target virtual addresses: %s").toString(),
        sourceVirtualAddress, sourceComponent, message.headers().get(TARGET_VIRTUAL_ADDRESSES));

    // Invia l'evento a tutti i target virtual addresses
    targetVirtualAddressesList.forEach(targetVirtualAddress -> {

      // Creare le opzioni di consegna desiderate
      DeliveryOptions options = new DeliveryOptions()
          .addHeader(SOURCE_VIRTUAL_ADDRESS, sourceVirtualAddress)
          .addHeader(SOURCE_COMPONENT, sourceComponent);

      log.debugf("Sending event message to target virtual address: %s", targetVirtualAddress);

      Uni<String> response = eventBus.<String>request(targetVirtualAddress, message.body())
          .onItem().transform(Message::body);

      response.subscribe().with(
          result -> {
            log.debugf("Received response from target virtual address: %s with result: %s",
                targetVirtualAddress, result);
          },
          failure -> {
            log.errorf(
                "Failed to receive response from target virtual address: %s with failure: %s",
                targetVirtualAddress, failure);
          }
      );
    });
  }
}
....

Passiamo adesso all'implementazione degli Event Handler. Questi componenti sono consumer registrati sull'Event Bus con gli indirizzi virtuali definiti in `app.eventbus.consumer.event.handler.addresses` sul file di configurazione `application.properties` dell'applicazione Quarkus.

Gli Event Handler sono responsabili di ricevere i messaggi dal Dispatcher, elaborarli e restituire l'esito dell'elaborazione. Implementeremo due Event Handler, uno per il tracciamento su un database NoSQL come https://www.mongodb.com/it-it[MongoDB] e l'altro per il tracciamento su un broker di messaggi come https://activemq.apache.org/components/artemis/[Apache ActiveMQ Artemis].

Lascerò a voi il compito della realizzazione dell'Event Handler per il tracciamento su un database SQL come https://www.mysql.com/[MySQL] o https://www.postgresql.org/[PostgreSQL]. Vi auguro quindi buon divertimento!
