== Progettiamo qualcosa di concreto

Ipotizziamo che per la nostra applicazione Quarkus sia richiesta la capacità di poter memorizzare le richieste/risposte https://en.wikipedia.org/wiki/Jakarta_RESTful_Web_Services[*JAX-RS* (Java API for RESTful Web Services)] che essa riceve. È inoltre richiesto che queste informazioni possano essere memorizzate su diversi supporti, come per esempio database SQL, database NoSQL o una coda https://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol#[AMQP (Advanced Message Queuing Protocol)].

Al fine di rendere più chiaro il requisito, a seguire è illustrato il diagramma che mostra come dovrà essere il flusso dell'applicazione, i componenti interessati e loro relazioni.

[mermaid, title="*Diagramma 2* - Flusso dell'applicazione Quarkus per lo storage delle richieste JAX-RS"]
....
graph TD
    A(User) -- HTTP Request --> E[Filtro JAX-RS];
    B(Mobile Device) -- HTTP Request --> E;
    C(Browser Web) -- HTTP Request --> E;
    D(Other Client) -- HTTP Request -->
    E -- Publish Event --> F[Event Bus];
    G[Consumers] --> H{O};
    G -.Subscribe to incoming http request -.-> F;
    G -.Subscribe to incoming http response -.-> F;
    H --> I[(Database SQL)];
    H --> L[(Database NoSQL)];
    H --> M(AMQP);

classDef yellow fill:#ffff00,stroke:#333,stroke-width:4px;
classDef green fill:#9F6,stroke:#333,stroke-width:2px;
classDef orange fill:#F96,stroke:#333,stroke-width:4px;
classDef garden fill:#65b889,stroke:#333,stroke-width:4px;
classDef beach fill:#b3b865,stroke:#333,stroke-width:2px;
classDef white fill:#FFFFFF,stroke:#333,stroke-width:2px;

class A,B,C,D green
class E orange
class F yellow
class G garden
class H white
class I,L,M beach
....

Stando al Diagramma 2, le richieste HTTP (verso i servizi REST) provenienti per esempio da utenti, dispositivi mobili, browser web o qualunque altro tipo di client, sono intercettate ed elaborate dal https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#filters[filtro JAX-RS] e successivamente pubblicate sull'Event Bus. I Consumer ricevono gli eventi per cui hanno la sottoscrizione, inviandoli poi, a seconda della configurazione e delle esigenze dell'applicazione, verso il Database SQL, Database NoSQL e la coda AMQP.

Ricordiamo che il filtro JAX-RS oltre a processare la request, processerà anche la response, motivo per cui gli eventi pubblicati sull'Event Bus saranno sia per la request sia per la response, di conseguenza ci saranno i rispettivi consumer. Il diagramma di sequenza a seguire aiuterà a capire meglio il ruolo del filtro JAX-RS.

[mermaid, title="*Diagramma 3* - Sequenza che illustra il flusso di dati attraverso un filtro JAX-RS all'interno dell'applicazione quando viene effettuata una richiesta da un client"]
....
sequenceDiagram
    autonumber
    participant Client
    participant Filter JAX-RS
    participant Resource Endpoint
    participant Application

 Client->>Application: Effettua una richiesta
 Application->>Filter JAX-RS: Chiamata alla richiesta JAX-RS
 Filter JAX-RS->>Resource Endpoint: Inoltro della richiesta
 Resource Endpoint-->>Filter JAX-RS: Risposta dalla risorsa
 Filter JAX-RS-->>Application: Risposta dal filtro
 Application-->>Client: Invio della risposta
....

Il diagramma di sequenza precedente mostra il flusso di dati attraverso un filtro JAX-RS all'interno dell'applicazione quando viene effettuata una richiesta da un client.

* Il Client effettua una richiesta all'https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#applications[applicazione].
* L'applicazione, ricevendo la richiesta, la passa attraverso il Filter JAX-RS.
* Il Filter JAX-RS inoltra la richiesta al https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#resources[Resource Endpoint] appropriato.
* Il Resource Endpoint elabora la richiesta e invia una risposta.
* Il Filter JAX-RS riceve la risposta dal Resource Endpoint e la passa indietro all'applicazione.
* Infine, l'applicazione invia la risposta al Client.

Il diagramma di sequenza a seguire aggiunge l'Event Bus e su questo sono pubblicati dal filtro JAX-RS i messaggi di richiesta e i messaggi di risposta (vedi step 4 e step 8) del servizio JAX-RS chiamato.

[mermaid, title="*Diagramma 4* - Estensione del diagramma precendente con l'aggiunta delle interazioni con l'Event Bus"]
....
sequenceDiagram
    autonumber
    participant Client
    participant Filter JAX-RS
    participant Resource Endpoint
    participant Event Bus
    participant Application

 Client->>Application: Effettua una richiesta
 Application->>Filter JAX-RS: Chiamata alla richiesta JAX-RS
 Filter JAX-RS->>Filter JAX-RS: Genera Messaggio
 Filter JAX-RS--)Event Bus: Pubblica Messaggio (async)
 Filter JAX-RS->>Resource Endpoint: Inoltro della richiesta
 Resource Endpoint-->>Filter JAX-RS: Risposta dalla risorsa
 Filter JAX-RS->>Filter JAX-RS: Genera Messaggio
 Filter JAX-RS--)Event Bus: Pubblica Messaggio (async)
 Filter JAX-RS-->>Application: Risposta dal filtro
 Application-->>Client: Invio della risposta
....

Quando i messaggi arrivano sul consumer, questi saranno elaborati dallo stesso e successivamente inviati al *Dispatcher* che sarà responsabile di veicolare il messaggio verso il corretto gestore (*Event Handler*) e quest'ultimo sarà l'effettivo responsabile dello store sul database SQL, NoSQL o sulla coda AMQP.

[mermaid, title="*Diagramma 5* - Utilizzo del Dispatcher per veicolare la richiesta di store delle richieste/risponste JAX-RS verso il sistema configurato."]
....
sequenceDiagram
    autonumber
    participant Consumer
    participant Dispatcher
    participant ehsql as Event Handler SQL
    participant ehnosql as Event Handler NoSQL
    participant ehqueue as Event Handler AMQP

Consumer ->> Consumer: Elabora Messaggio
Consumer-)Dispatcher: Invia messaggio

alt Event Handler SQL enabled
  Dispatcher-)ehsql: Inoltra l'evento (async)
  ehsql-)Dispatcher: Notifica l'elaborazione
	else Event Handler NoSQL enabled
  Dispatcher-)ehnosql: Inoltra l'evento (async)
  ehnosql-)Dispatcher: Notifica l'elaborazione
else Event Handler AMQP enabled
  Dispatcher-)ehqueue: Inoltra l'evento (async)
  ehqueue-)Dispatcher: Notifica l'elaborazione
end
....

Il blocco _alt (abbreviazione di "alternative")_ del diagramma di sequenza precedente mostra come il Dispatcher inoltra l'evento all'Event Handler SQL, NoSQL o AMQP in base alla configurazione dell'applicazione. Nel diagramma di flusso precedente (diagramma 2), il Dispatcher è rappresentato dall'https://en.wikipedia.org/wiki/Business_Process_Model_and_Notation[Inclusive Gateway (notazione BPMN)].  Le operazioni del blocco alt sono asincrone, per cui l'ordine l'ordine di esecuzione delle operazioni non è garantito. Una volta che l'Event Handler ha elaborato l'evento, notifica il Dispatcher dell'esito dell'operazione.