== Conclusioni

L'Event Bus di Quarkus si presenta come una potente e flessibile risorsa per la gestione degli eventi all'interno delle moderne applicazioni Java. Grazie alla sua integrazione nativa con il framework Quarkus e l'utilizzo del motore di eventi di Vert.x, l'Event Bus offre una serie di utilizzi e vantaggi significativi per gli sviluppatori.

Nel corso dell'articolo abbiamo descritto i campi di applicazione dell'Event Bus e abbiamo affrontato in modo concreto la progettazione e implementazione di un sistema per il tracciamento delle richieste e delle risposte HTTP in un'applicazione Quarkus utilizzando l'Event Bus, riscontrando come sia stato difatto abbastanza semplice creare questo sistema dove ogni singolo componente è responsabile di un'azione specifica e comunica con gli altri componenti attraverso la pubblicazione e sottoscrizione di messaggi.

A dimostrazione del fatto che Quarkus sia nato per essere cloud native, abbiamo visto come sia stato semplice effettuare il deploy dell'applicazione Quarkus su OpenShift, un ambiente cloud native, e come sia stato possibile configurare l'applicazione Quarkus per connettersi alle risorse esterne come il broker AMQP Apache ActiveMQ Artemis e il database NoSQL MongoDB.
